from dispather import register


def handle_unknown(event , n , repo) : print(f"-{event} {n} UNKNOWN to  {repo}") 


@register("WatchEvent")
def handle_watch(event , n , repo) :   print(f"-Watched {n} times  to {repo}")
@register("PushEvent")
def handle_push(event , n , repo) :    print(f"-{event}  {n} commits to  {repo}")
@register("ForkEvent")
def  handle_fork(event , n , repo) : print(f"-Forked {n} times to  {repo}")
@register("CreateEvent")
def handle_create(event , n , repo) : print(f"-Started to   {repo}")
@register("DeleteEvent")
def handle_delete(event , n , repo ) :  print(f"-Deleted to  {repo}")
@register("IssuesEvent")
def handle_open(event , n , repo) : print(f"-Opened a new issue to  {repo} {n} times")
@register("IssueCommentEvent")
def handle_close(event , n  , repo): print(f"-Closed an issue to  {repo} {n} times") 
@register("ReleaseEvent")
def handle_release(event , n, repo) : print(f"-Created release(s) {n} to  {repo}")
@register("GollumEvent")
def handle_gollum(event , n , repo) : print(f"-Created wiki page(s) {n} to   {repo}")
@register("MemberEvent")
def handle_member(event , n, repo) : print(f"-Added member(s) {n} to {repo}")
@register("PublicEvent")
def handle_public(event , n , repo) : print(f"-Publicized to  {repo}") 
@register("TeamEvent")
def handle_team(event , n ,repo) : print(f"-Added team(s) {n} to {repo}")
@register("SponsorshipEvent")
def handle_sponsorship(event , n , repo) : print(f"-Created sponsorship(s) {n} to {repo}")
@register("DeploymentEvent")
def handle_deployment(event , n ,repo) : print(f"-Created deployment(s) {n} to  {repo}")
@register("DeploymentStatusEvent")
def handle_deployment_status(event , n ,repo) : print(f"-Created deployment status(es) {n} to {repo}")
@register("PackageEvent")
def handle_package(event , n , repo) : print(f"-Created package(s) {n} to  {repo}")
@register("ImportEvent")
def handle_import(event , n , repo) : print(f"-Started to import {repo}")
@register("PushDeleteEvent")
def handle_push_delete(event , n ,repo) : print(f"-Pushed to {repo} and deleted it")
@register("PullRequestEvent")
def handle_pull_request(event , n ,repo) : print(f"-Created pull request(s) {n} to  {repo}")
@register("PullRequestReviewEvent")
def handle_pull_request_review(event , n , repo) : print(f"-Created pull request review(s) {n} to  {repo}")
@register("PullRequestReviewCommentEvent")
def handle_pull_request_review_comment(event , n ,repo) : print(f"-Created pull request review comment(s) {n} to  {repo}")
@register("CommitCommentEvent")
def handle_commit_comment(event , n ,repo) : print(f"-Created commit comment(s) {n} to  {repo}")
@register("ReleaseDeleteEvent")
def handle_release_delete(event , n,repo) : print(f"-Deleted release to  {repo}")
@register("GollumDeleteEvent")
def handle_gollum_delete(event , n , repo) : print(f"-Deleted wiki page(s) {n} to  {repo}")
@register ("MemberDeleteEvent")
def handle_member_delete(event , n , repo) : print(f"-Deleted member(s) {n} to  {repo}")
@register("TeamDeleteEvent")
def handle_team_delete(event , n , repo) : print(f"-Deleted team(s) {n} to  {repo}")
@register("SponsorshipDeleteEvent")
def handle_sponsorship_delete(event , n ,repo) : print(f"-Deleted sponsorship(s) {n} to  {repo}")



